
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ActiveMember` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ActiveMember
 * 
 */
export type ActiveMemberModel = runtime.Types.Result.DefaultSelection<Prisma.$ActiveMemberPayload>

export type AggregateActiveMember = {
  _count: ActiveMemberCountAggregateOutputType | null
  _min: ActiveMemberMinAggregateOutputType | null
  _max: ActiveMemberMaxAggregateOutputType | null
}

export type ActiveMemberMinAggregateOutputType = {
  id: string | null
  user_id: string | null
  channel_id: string | null
  connected_at: Date | null
}

export type ActiveMemberMaxAggregateOutputType = {
  id: string | null
  user_id: string | null
  channel_id: string | null
  connected_at: Date | null
}

export type ActiveMemberCountAggregateOutputType = {
  id: number
  user_id: number
  channel_id: number
  connected_at: number
  _all: number
}


export type ActiveMemberMinAggregateInputType = {
  id?: true
  user_id?: true
  channel_id?: true
  connected_at?: true
}

export type ActiveMemberMaxAggregateInputType = {
  id?: true
  user_id?: true
  channel_id?: true
  connected_at?: true
}

export type ActiveMemberCountAggregateInputType = {
  id?: true
  user_id?: true
  channel_id?: true
  connected_at?: true
  _all?: true
}

export type ActiveMemberAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ActiveMember to aggregate.
   */
  where?: Prisma.ActiveMemberWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ActiveMembers to fetch.
   */
  orderBy?: Prisma.ActiveMemberOrderByWithRelationInput | Prisma.ActiveMemberOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ActiveMemberWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ActiveMembers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ActiveMembers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ActiveMembers
  **/
  _count?: true | ActiveMemberCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ActiveMemberMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ActiveMemberMaxAggregateInputType
}

export type GetActiveMemberAggregateType<T extends ActiveMemberAggregateArgs> = {
      [P in keyof T & keyof AggregateActiveMember]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateActiveMember[P]>
    : Prisma.GetScalarType<T[P], AggregateActiveMember[P]>
}




export type ActiveMemberGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ActiveMemberWhereInput
  orderBy?: Prisma.ActiveMemberOrderByWithAggregationInput | Prisma.ActiveMemberOrderByWithAggregationInput[]
  by: Prisma.ActiveMemberScalarFieldEnum[] | Prisma.ActiveMemberScalarFieldEnum
  having?: Prisma.ActiveMemberScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ActiveMemberCountAggregateInputType | true
  _min?: ActiveMemberMinAggregateInputType
  _max?: ActiveMemberMaxAggregateInputType
}

export type ActiveMemberGroupByOutputType = {
  id: string
  user_id: string
  channel_id: string
  connected_at: Date
  _count: ActiveMemberCountAggregateOutputType | null
  _min: ActiveMemberMinAggregateOutputType | null
  _max: ActiveMemberMaxAggregateOutputType | null
}

type GetActiveMemberGroupByPayload<T extends ActiveMemberGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ActiveMemberGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ActiveMemberGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ActiveMemberGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ActiveMemberGroupByOutputType[P]>
      }
    >
  >



export type ActiveMemberWhereInput = {
  AND?: Prisma.ActiveMemberWhereInput | Prisma.ActiveMemberWhereInput[]
  OR?: Prisma.ActiveMemberWhereInput[]
  NOT?: Prisma.ActiveMemberWhereInput | Prisma.ActiveMemberWhereInput[]
  id?: Prisma.StringFilter<"ActiveMember"> | string
  user_id?: Prisma.StringFilter<"ActiveMember"> | string
  channel_id?: Prisma.StringFilter<"ActiveMember"> | string
  connected_at?: Prisma.DateTimeFilter<"ActiveMember"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  channel?: Prisma.XOR<Prisma.ChannelScalarRelationFilter, Prisma.ChannelWhereInput>
}

export type ActiveMemberOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  channel_id?: Prisma.SortOrder
  connected_at?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  channel?: Prisma.ChannelOrderByWithRelationInput
}

export type ActiveMemberWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  member_channel_unique?: Prisma.ActiveMemberMember_channel_uniqueCompoundUniqueInput
  AND?: Prisma.ActiveMemberWhereInput | Prisma.ActiveMemberWhereInput[]
  OR?: Prisma.ActiveMemberWhereInput[]
  NOT?: Prisma.ActiveMemberWhereInput | Prisma.ActiveMemberWhereInput[]
  user_id?: Prisma.StringFilter<"ActiveMember"> | string
  channel_id?: Prisma.StringFilter<"ActiveMember"> | string
  connected_at?: Prisma.DateTimeFilter<"ActiveMember"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  channel?: Prisma.XOR<Prisma.ChannelScalarRelationFilter, Prisma.ChannelWhereInput>
}, "id" | "member_channel_unique">

export type ActiveMemberOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  channel_id?: Prisma.SortOrder
  connected_at?: Prisma.SortOrder
  _count?: Prisma.ActiveMemberCountOrderByAggregateInput
  _max?: Prisma.ActiveMemberMaxOrderByAggregateInput
  _min?: Prisma.ActiveMemberMinOrderByAggregateInput
}

export type ActiveMemberScalarWhereWithAggregatesInput = {
  AND?: Prisma.ActiveMemberScalarWhereWithAggregatesInput | Prisma.ActiveMemberScalarWhereWithAggregatesInput[]
  OR?: Prisma.ActiveMemberScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ActiveMemberScalarWhereWithAggregatesInput | Prisma.ActiveMemberScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ActiveMember"> | string
  user_id?: Prisma.StringWithAggregatesFilter<"ActiveMember"> | string
  channel_id?: Prisma.StringWithAggregatesFilter<"ActiveMember"> | string
  connected_at?: Prisma.DateTimeWithAggregatesFilter<"ActiveMember"> | Date | string
}

export type ActiveMemberCreateInput = {
  id?: string
  connected_at?: Date | string
  user: Prisma.UserCreateNestedOneWithoutActiveMembersInput
  channel: Prisma.ChannelCreateNestedOneWithoutActiveMembersInput
}

export type ActiveMemberUncheckedCreateInput = {
  id?: string
  user_id: string
  channel_id: string
  connected_at?: Date | string
}

export type ActiveMemberUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  connected_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutActiveMembersNestedInput
  channel?: Prisma.ChannelUpdateOneRequiredWithoutActiveMembersNestedInput
}

export type ActiveMemberUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  channel_id?: Prisma.StringFieldUpdateOperationsInput | string
  connected_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ActiveMemberCreateManyInput = {
  id?: string
  user_id: string
  channel_id: string
  connected_at?: Date | string
}

export type ActiveMemberUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  connected_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ActiveMemberUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  channel_id?: Prisma.StringFieldUpdateOperationsInput | string
  connected_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ActiveMemberListRelationFilter = {
  every?: Prisma.ActiveMemberWhereInput
  some?: Prisma.ActiveMemberWhereInput
  none?: Prisma.ActiveMemberWhereInput
}

export type ActiveMemberOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ActiveMemberMember_channel_uniqueCompoundUniqueInput = {
  user_id: string
  channel_id: string
}

export type ActiveMemberCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  channel_id?: Prisma.SortOrder
  connected_at?: Prisma.SortOrder
}

export type ActiveMemberMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  channel_id?: Prisma.SortOrder
  connected_at?: Prisma.SortOrder
}

export type ActiveMemberMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  channel_id?: Prisma.SortOrder
  connected_at?: Prisma.SortOrder
}

export type ActiveMemberCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ActiveMemberCreateWithoutUserInput, Prisma.ActiveMemberUncheckedCreateWithoutUserInput> | Prisma.ActiveMemberCreateWithoutUserInput[] | Prisma.ActiveMemberUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ActiveMemberCreateOrConnectWithoutUserInput | Prisma.ActiveMemberCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ActiveMemberCreateManyUserInputEnvelope
  connect?: Prisma.ActiveMemberWhereUniqueInput | Prisma.ActiveMemberWhereUniqueInput[]
}

export type ActiveMemberUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ActiveMemberCreateWithoutUserInput, Prisma.ActiveMemberUncheckedCreateWithoutUserInput> | Prisma.ActiveMemberCreateWithoutUserInput[] | Prisma.ActiveMemberUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ActiveMemberCreateOrConnectWithoutUserInput | Prisma.ActiveMemberCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ActiveMemberCreateManyUserInputEnvelope
  connect?: Prisma.ActiveMemberWhereUniqueInput | Prisma.ActiveMemberWhereUniqueInput[]
}

export type ActiveMemberUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ActiveMemberCreateWithoutUserInput, Prisma.ActiveMemberUncheckedCreateWithoutUserInput> | Prisma.ActiveMemberCreateWithoutUserInput[] | Prisma.ActiveMemberUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ActiveMemberCreateOrConnectWithoutUserInput | Prisma.ActiveMemberCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ActiveMemberUpsertWithWhereUniqueWithoutUserInput | Prisma.ActiveMemberUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ActiveMemberCreateManyUserInputEnvelope
  set?: Prisma.ActiveMemberWhereUniqueInput | Prisma.ActiveMemberWhereUniqueInput[]
  disconnect?: Prisma.ActiveMemberWhereUniqueInput | Prisma.ActiveMemberWhereUniqueInput[]
  delete?: Prisma.ActiveMemberWhereUniqueInput | Prisma.ActiveMemberWhereUniqueInput[]
  connect?: Prisma.ActiveMemberWhereUniqueInput | Prisma.ActiveMemberWhereUniqueInput[]
  update?: Prisma.ActiveMemberUpdateWithWhereUniqueWithoutUserInput | Prisma.ActiveMemberUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ActiveMemberUpdateManyWithWhereWithoutUserInput | Prisma.ActiveMemberUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ActiveMemberScalarWhereInput | Prisma.ActiveMemberScalarWhereInput[]
}

export type ActiveMemberUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ActiveMemberCreateWithoutUserInput, Prisma.ActiveMemberUncheckedCreateWithoutUserInput> | Prisma.ActiveMemberCreateWithoutUserInput[] | Prisma.ActiveMemberUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ActiveMemberCreateOrConnectWithoutUserInput | Prisma.ActiveMemberCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ActiveMemberUpsertWithWhereUniqueWithoutUserInput | Prisma.ActiveMemberUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ActiveMemberCreateManyUserInputEnvelope
  set?: Prisma.ActiveMemberWhereUniqueInput | Prisma.ActiveMemberWhereUniqueInput[]
  disconnect?: Prisma.ActiveMemberWhereUniqueInput | Prisma.ActiveMemberWhereUniqueInput[]
  delete?: Prisma.ActiveMemberWhereUniqueInput | Prisma.ActiveMemberWhereUniqueInput[]
  connect?: Prisma.ActiveMemberWhereUniqueInput | Prisma.ActiveMemberWhereUniqueInput[]
  update?: Prisma.ActiveMemberUpdateWithWhereUniqueWithoutUserInput | Prisma.ActiveMemberUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ActiveMemberUpdateManyWithWhereWithoutUserInput | Prisma.ActiveMemberUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ActiveMemberScalarWhereInput | Prisma.ActiveMemberScalarWhereInput[]
}

export type ActiveMemberCreateNestedManyWithoutChannelInput = {
  create?: Prisma.XOR<Prisma.ActiveMemberCreateWithoutChannelInput, Prisma.ActiveMemberUncheckedCreateWithoutChannelInput> | Prisma.ActiveMemberCreateWithoutChannelInput[] | Prisma.ActiveMemberUncheckedCreateWithoutChannelInput[]
  connectOrCreate?: Prisma.ActiveMemberCreateOrConnectWithoutChannelInput | Prisma.ActiveMemberCreateOrConnectWithoutChannelInput[]
  createMany?: Prisma.ActiveMemberCreateManyChannelInputEnvelope
  connect?: Prisma.ActiveMemberWhereUniqueInput | Prisma.ActiveMemberWhereUniqueInput[]
}

export type ActiveMemberUncheckedCreateNestedManyWithoutChannelInput = {
  create?: Prisma.XOR<Prisma.ActiveMemberCreateWithoutChannelInput, Prisma.ActiveMemberUncheckedCreateWithoutChannelInput> | Prisma.ActiveMemberCreateWithoutChannelInput[] | Prisma.ActiveMemberUncheckedCreateWithoutChannelInput[]
  connectOrCreate?: Prisma.ActiveMemberCreateOrConnectWithoutChannelInput | Prisma.ActiveMemberCreateOrConnectWithoutChannelInput[]
  createMany?: Prisma.ActiveMemberCreateManyChannelInputEnvelope
  connect?: Prisma.ActiveMemberWhereUniqueInput | Prisma.ActiveMemberWhereUniqueInput[]
}

export type ActiveMemberUpdateManyWithoutChannelNestedInput = {
  create?: Prisma.XOR<Prisma.ActiveMemberCreateWithoutChannelInput, Prisma.ActiveMemberUncheckedCreateWithoutChannelInput> | Prisma.ActiveMemberCreateWithoutChannelInput[] | Prisma.ActiveMemberUncheckedCreateWithoutChannelInput[]
  connectOrCreate?: Prisma.ActiveMemberCreateOrConnectWithoutChannelInput | Prisma.ActiveMemberCreateOrConnectWithoutChannelInput[]
  upsert?: Prisma.ActiveMemberUpsertWithWhereUniqueWithoutChannelInput | Prisma.ActiveMemberUpsertWithWhereUniqueWithoutChannelInput[]
  createMany?: Prisma.ActiveMemberCreateManyChannelInputEnvelope
  set?: Prisma.ActiveMemberWhereUniqueInput | Prisma.ActiveMemberWhereUniqueInput[]
  disconnect?: Prisma.ActiveMemberWhereUniqueInput | Prisma.ActiveMemberWhereUniqueInput[]
  delete?: Prisma.ActiveMemberWhereUniqueInput | Prisma.ActiveMemberWhereUniqueInput[]
  connect?: Prisma.ActiveMemberWhereUniqueInput | Prisma.ActiveMemberWhereUniqueInput[]
  update?: Prisma.ActiveMemberUpdateWithWhereUniqueWithoutChannelInput | Prisma.ActiveMemberUpdateWithWhereUniqueWithoutChannelInput[]
  updateMany?: Prisma.ActiveMemberUpdateManyWithWhereWithoutChannelInput | Prisma.ActiveMemberUpdateManyWithWhereWithoutChannelInput[]
  deleteMany?: Prisma.ActiveMemberScalarWhereInput | Prisma.ActiveMemberScalarWhereInput[]
}

export type ActiveMemberUncheckedUpdateManyWithoutChannelNestedInput = {
  create?: Prisma.XOR<Prisma.ActiveMemberCreateWithoutChannelInput, Prisma.ActiveMemberUncheckedCreateWithoutChannelInput> | Prisma.ActiveMemberCreateWithoutChannelInput[] | Prisma.ActiveMemberUncheckedCreateWithoutChannelInput[]
  connectOrCreate?: Prisma.ActiveMemberCreateOrConnectWithoutChannelInput | Prisma.ActiveMemberCreateOrConnectWithoutChannelInput[]
  upsert?: Prisma.ActiveMemberUpsertWithWhereUniqueWithoutChannelInput | Prisma.ActiveMemberUpsertWithWhereUniqueWithoutChannelInput[]
  createMany?: Prisma.ActiveMemberCreateManyChannelInputEnvelope
  set?: Prisma.ActiveMemberWhereUniqueInput | Prisma.ActiveMemberWhereUniqueInput[]
  disconnect?: Prisma.ActiveMemberWhereUniqueInput | Prisma.ActiveMemberWhereUniqueInput[]
  delete?: Prisma.ActiveMemberWhereUniqueInput | Prisma.ActiveMemberWhereUniqueInput[]
  connect?: Prisma.ActiveMemberWhereUniqueInput | Prisma.ActiveMemberWhereUniqueInput[]
  update?: Prisma.ActiveMemberUpdateWithWhereUniqueWithoutChannelInput | Prisma.ActiveMemberUpdateWithWhereUniqueWithoutChannelInput[]
  updateMany?: Prisma.ActiveMemberUpdateManyWithWhereWithoutChannelInput | Prisma.ActiveMemberUpdateManyWithWhereWithoutChannelInput[]
  deleteMany?: Prisma.ActiveMemberScalarWhereInput | Prisma.ActiveMemberScalarWhereInput[]
}

export type ActiveMemberCreateWithoutUserInput = {
  id?: string
  connected_at?: Date | string
  channel: Prisma.ChannelCreateNestedOneWithoutActiveMembersInput
}

export type ActiveMemberUncheckedCreateWithoutUserInput = {
  id?: string
  channel_id: string
  connected_at?: Date | string
}

export type ActiveMemberCreateOrConnectWithoutUserInput = {
  where: Prisma.ActiveMemberWhereUniqueInput
  create: Prisma.XOR<Prisma.ActiveMemberCreateWithoutUserInput, Prisma.ActiveMemberUncheckedCreateWithoutUserInput>
}

export type ActiveMemberCreateManyUserInputEnvelope = {
  data: Prisma.ActiveMemberCreateManyUserInput | Prisma.ActiveMemberCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type ActiveMemberUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.ActiveMemberWhereUniqueInput
  update: Prisma.XOR<Prisma.ActiveMemberUpdateWithoutUserInput, Prisma.ActiveMemberUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.ActiveMemberCreateWithoutUserInput, Prisma.ActiveMemberUncheckedCreateWithoutUserInput>
}

export type ActiveMemberUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.ActiveMemberWhereUniqueInput
  data: Prisma.XOR<Prisma.ActiveMemberUpdateWithoutUserInput, Prisma.ActiveMemberUncheckedUpdateWithoutUserInput>
}

export type ActiveMemberUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.ActiveMemberScalarWhereInput
  data: Prisma.XOR<Prisma.ActiveMemberUpdateManyMutationInput, Prisma.ActiveMemberUncheckedUpdateManyWithoutUserInput>
}

export type ActiveMemberScalarWhereInput = {
  AND?: Prisma.ActiveMemberScalarWhereInput | Prisma.ActiveMemberScalarWhereInput[]
  OR?: Prisma.ActiveMemberScalarWhereInput[]
  NOT?: Prisma.ActiveMemberScalarWhereInput | Prisma.ActiveMemberScalarWhereInput[]
  id?: Prisma.StringFilter<"ActiveMember"> | string
  user_id?: Prisma.StringFilter<"ActiveMember"> | string
  channel_id?: Prisma.StringFilter<"ActiveMember"> | string
  connected_at?: Prisma.DateTimeFilter<"ActiveMember"> | Date | string
}

export type ActiveMemberCreateWithoutChannelInput = {
  id?: string
  connected_at?: Date | string
  user: Prisma.UserCreateNestedOneWithoutActiveMembersInput
}

export type ActiveMemberUncheckedCreateWithoutChannelInput = {
  id?: string
  user_id: string
  connected_at?: Date | string
}

export type ActiveMemberCreateOrConnectWithoutChannelInput = {
  where: Prisma.ActiveMemberWhereUniqueInput
  create: Prisma.XOR<Prisma.ActiveMemberCreateWithoutChannelInput, Prisma.ActiveMemberUncheckedCreateWithoutChannelInput>
}

export type ActiveMemberCreateManyChannelInputEnvelope = {
  data: Prisma.ActiveMemberCreateManyChannelInput | Prisma.ActiveMemberCreateManyChannelInput[]
  skipDuplicates?: boolean
}

export type ActiveMemberUpsertWithWhereUniqueWithoutChannelInput = {
  where: Prisma.ActiveMemberWhereUniqueInput
  update: Prisma.XOR<Prisma.ActiveMemberUpdateWithoutChannelInput, Prisma.ActiveMemberUncheckedUpdateWithoutChannelInput>
  create: Prisma.XOR<Prisma.ActiveMemberCreateWithoutChannelInput, Prisma.ActiveMemberUncheckedCreateWithoutChannelInput>
}

export type ActiveMemberUpdateWithWhereUniqueWithoutChannelInput = {
  where: Prisma.ActiveMemberWhereUniqueInput
  data: Prisma.XOR<Prisma.ActiveMemberUpdateWithoutChannelInput, Prisma.ActiveMemberUncheckedUpdateWithoutChannelInput>
}

export type ActiveMemberUpdateManyWithWhereWithoutChannelInput = {
  where: Prisma.ActiveMemberScalarWhereInput
  data: Prisma.XOR<Prisma.ActiveMemberUpdateManyMutationInput, Prisma.ActiveMemberUncheckedUpdateManyWithoutChannelInput>
}

export type ActiveMemberCreateManyUserInput = {
  id?: string
  channel_id: string
  connected_at?: Date | string
}

export type ActiveMemberUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  connected_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  channel?: Prisma.ChannelUpdateOneRequiredWithoutActiveMembersNestedInput
}

export type ActiveMemberUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channel_id?: Prisma.StringFieldUpdateOperationsInput | string
  connected_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ActiveMemberUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channel_id?: Prisma.StringFieldUpdateOperationsInput | string
  connected_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ActiveMemberCreateManyChannelInput = {
  id?: string
  user_id: string
  connected_at?: Date | string
}

export type ActiveMemberUpdateWithoutChannelInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  connected_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutActiveMembersNestedInput
}

export type ActiveMemberUncheckedUpdateWithoutChannelInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  connected_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ActiveMemberUncheckedUpdateManyWithoutChannelInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  connected_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ActiveMemberSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  channel_id?: boolean
  connected_at?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  channel?: boolean | Prisma.ChannelDefaultArgs<ExtArgs>
}, ExtArgs["result"]["activeMember"]>

export type ActiveMemberSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  channel_id?: boolean
  connected_at?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  channel?: boolean | Prisma.ChannelDefaultArgs<ExtArgs>
}, ExtArgs["result"]["activeMember"]>

export type ActiveMemberSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  channel_id?: boolean
  connected_at?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  channel?: boolean | Prisma.ChannelDefaultArgs<ExtArgs>
}, ExtArgs["result"]["activeMember"]>

export type ActiveMemberSelectScalar = {
  id?: boolean
  user_id?: boolean
  channel_id?: boolean
  connected_at?: boolean
}

export type ActiveMemberOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "user_id" | "channel_id" | "connected_at", ExtArgs["result"]["activeMember"]>
export type ActiveMemberInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  channel?: boolean | Prisma.ChannelDefaultArgs<ExtArgs>
}
export type ActiveMemberIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  channel?: boolean | Prisma.ChannelDefaultArgs<ExtArgs>
}
export type ActiveMemberIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  channel?: boolean | Prisma.ChannelDefaultArgs<ExtArgs>
}

export type $ActiveMemberPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ActiveMember"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    channel: Prisma.$ChannelPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    user_id: string
    channel_id: string
    connected_at: Date
  }, ExtArgs["result"]["activeMember"]>
  composites: {}
}

export type ActiveMemberGetPayload<S extends boolean | null | undefined | ActiveMemberDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ActiveMemberPayload, S>

export type ActiveMemberCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ActiveMemberFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ActiveMemberCountAggregateInputType | true
  }

export interface ActiveMemberDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ActiveMember'], meta: { name: 'ActiveMember' } }
  /**
   * Find zero or one ActiveMember that matches the filter.
   * @param {ActiveMemberFindUniqueArgs} args - Arguments to find a ActiveMember
   * @example
   * // Get one ActiveMember
   * const activeMember = await prisma.activeMember.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ActiveMemberFindUniqueArgs>(args: Prisma.SelectSubset<T, ActiveMemberFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ActiveMemberClient<runtime.Types.Result.GetResult<Prisma.$ActiveMemberPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ActiveMember that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ActiveMemberFindUniqueOrThrowArgs} args - Arguments to find a ActiveMember
   * @example
   * // Get one ActiveMember
   * const activeMember = await prisma.activeMember.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ActiveMemberFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ActiveMemberFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ActiveMemberClient<runtime.Types.Result.GetResult<Prisma.$ActiveMemberPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ActiveMember that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActiveMemberFindFirstArgs} args - Arguments to find a ActiveMember
   * @example
   * // Get one ActiveMember
   * const activeMember = await prisma.activeMember.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ActiveMemberFindFirstArgs>(args?: Prisma.SelectSubset<T, ActiveMemberFindFirstArgs<ExtArgs>>): Prisma.Prisma__ActiveMemberClient<runtime.Types.Result.GetResult<Prisma.$ActiveMemberPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ActiveMember that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActiveMemberFindFirstOrThrowArgs} args - Arguments to find a ActiveMember
   * @example
   * // Get one ActiveMember
   * const activeMember = await prisma.activeMember.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ActiveMemberFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ActiveMemberFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ActiveMemberClient<runtime.Types.Result.GetResult<Prisma.$ActiveMemberPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ActiveMembers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActiveMemberFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ActiveMembers
   * const activeMembers = await prisma.activeMember.findMany()
   * 
   * // Get first 10 ActiveMembers
   * const activeMembers = await prisma.activeMember.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const activeMemberWithIdOnly = await prisma.activeMember.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ActiveMemberFindManyArgs>(args?: Prisma.SelectSubset<T, ActiveMemberFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ActiveMemberPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ActiveMember.
   * @param {ActiveMemberCreateArgs} args - Arguments to create a ActiveMember.
   * @example
   * // Create one ActiveMember
   * const ActiveMember = await prisma.activeMember.create({
   *   data: {
   *     // ... data to create a ActiveMember
   *   }
   * })
   * 
   */
  create<T extends ActiveMemberCreateArgs>(args: Prisma.SelectSubset<T, ActiveMemberCreateArgs<ExtArgs>>): Prisma.Prisma__ActiveMemberClient<runtime.Types.Result.GetResult<Prisma.$ActiveMemberPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ActiveMembers.
   * @param {ActiveMemberCreateManyArgs} args - Arguments to create many ActiveMembers.
   * @example
   * // Create many ActiveMembers
   * const activeMember = await prisma.activeMember.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ActiveMemberCreateManyArgs>(args?: Prisma.SelectSubset<T, ActiveMemberCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ActiveMembers and returns the data saved in the database.
   * @param {ActiveMemberCreateManyAndReturnArgs} args - Arguments to create many ActiveMembers.
   * @example
   * // Create many ActiveMembers
   * const activeMember = await prisma.activeMember.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ActiveMembers and only return the `id`
   * const activeMemberWithIdOnly = await prisma.activeMember.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ActiveMemberCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ActiveMemberCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ActiveMemberPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ActiveMember.
   * @param {ActiveMemberDeleteArgs} args - Arguments to delete one ActiveMember.
   * @example
   * // Delete one ActiveMember
   * const ActiveMember = await prisma.activeMember.delete({
   *   where: {
   *     // ... filter to delete one ActiveMember
   *   }
   * })
   * 
   */
  delete<T extends ActiveMemberDeleteArgs>(args: Prisma.SelectSubset<T, ActiveMemberDeleteArgs<ExtArgs>>): Prisma.Prisma__ActiveMemberClient<runtime.Types.Result.GetResult<Prisma.$ActiveMemberPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ActiveMember.
   * @param {ActiveMemberUpdateArgs} args - Arguments to update one ActiveMember.
   * @example
   * // Update one ActiveMember
   * const activeMember = await prisma.activeMember.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ActiveMemberUpdateArgs>(args: Prisma.SelectSubset<T, ActiveMemberUpdateArgs<ExtArgs>>): Prisma.Prisma__ActiveMemberClient<runtime.Types.Result.GetResult<Prisma.$ActiveMemberPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ActiveMembers.
   * @param {ActiveMemberDeleteManyArgs} args - Arguments to filter ActiveMembers to delete.
   * @example
   * // Delete a few ActiveMembers
   * const { count } = await prisma.activeMember.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ActiveMemberDeleteManyArgs>(args?: Prisma.SelectSubset<T, ActiveMemberDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ActiveMembers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActiveMemberUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ActiveMembers
   * const activeMember = await prisma.activeMember.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ActiveMemberUpdateManyArgs>(args: Prisma.SelectSubset<T, ActiveMemberUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ActiveMembers and returns the data updated in the database.
   * @param {ActiveMemberUpdateManyAndReturnArgs} args - Arguments to update many ActiveMembers.
   * @example
   * // Update many ActiveMembers
   * const activeMember = await prisma.activeMember.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ActiveMembers and only return the `id`
   * const activeMemberWithIdOnly = await prisma.activeMember.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ActiveMemberUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ActiveMemberUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ActiveMemberPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ActiveMember.
   * @param {ActiveMemberUpsertArgs} args - Arguments to update or create a ActiveMember.
   * @example
   * // Update or create a ActiveMember
   * const activeMember = await prisma.activeMember.upsert({
   *   create: {
   *     // ... data to create a ActiveMember
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ActiveMember we want to update
   *   }
   * })
   */
  upsert<T extends ActiveMemberUpsertArgs>(args: Prisma.SelectSubset<T, ActiveMemberUpsertArgs<ExtArgs>>): Prisma.Prisma__ActiveMemberClient<runtime.Types.Result.GetResult<Prisma.$ActiveMemberPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ActiveMembers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActiveMemberCountArgs} args - Arguments to filter ActiveMembers to count.
   * @example
   * // Count the number of ActiveMembers
   * const count = await prisma.activeMember.count({
   *   where: {
   *     // ... the filter for the ActiveMembers we want to count
   *   }
   * })
  **/
  count<T extends ActiveMemberCountArgs>(
    args?: Prisma.Subset<T, ActiveMemberCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ActiveMemberCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ActiveMember.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActiveMemberAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ActiveMemberAggregateArgs>(args: Prisma.Subset<T, ActiveMemberAggregateArgs>): Prisma.PrismaPromise<GetActiveMemberAggregateType<T>>

  /**
   * Group by ActiveMember.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActiveMemberGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ActiveMemberGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ActiveMemberGroupByArgs['orderBy'] }
      : { orderBy?: ActiveMemberGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ActiveMemberGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetActiveMemberGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ActiveMember model
 */
readonly fields: ActiveMemberFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ActiveMember.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ActiveMemberClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  channel<T extends Prisma.ChannelDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ChannelDefaultArgs<ExtArgs>>): Prisma.Prisma__ChannelClient<runtime.Types.Result.GetResult<Prisma.$ChannelPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ActiveMember model
 */
export interface ActiveMemberFieldRefs {
  readonly id: Prisma.FieldRef<"ActiveMember", 'String'>
  readonly user_id: Prisma.FieldRef<"ActiveMember", 'String'>
  readonly channel_id: Prisma.FieldRef<"ActiveMember", 'String'>
  readonly connected_at: Prisma.FieldRef<"ActiveMember", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ActiveMember findUnique
 */
export type ActiveMemberFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActiveMember
   */
  select?: Prisma.ActiveMemberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActiveMember
   */
  omit?: Prisma.ActiveMemberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActiveMemberInclude<ExtArgs> | null
  /**
   * Filter, which ActiveMember to fetch.
   */
  where: Prisma.ActiveMemberWhereUniqueInput
}

/**
 * ActiveMember findUniqueOrThrow
 */
export type ActiveMemberFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActiveMember
   */
  select?: Prisma.ActiveMemberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActiveMember
   */
  omit?: Prisma.ActiveMemberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActiveMemberInclude<ExtArgs> | null
  /**
   * Filter, which ActiveMember to fetch.
   */
  where: Prisma.ActiveMemberWhereUniqueInput
}

/**
 * ActiveMember findFirst
 */
export type ActiveMemberFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActiveMember
   */
  select?: Prisma.ActiveMemberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActiveMember
   */
  omit?: Prisma.ActiveMemberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActiveMemberInclude<ExtArgs> | null
  /**
   * Filter, which ActiveMember to fetch.
   */
  where?: Prisma.ActiveMemberWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ActiveMembers to fetch.
   */
  orderBy?: Prisma.ActiveMemberOrderByWithRelationInput | Prisma.ActiveMemberOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ActiveMembers.
   */
  cursor?: Prisma.ActiveMemberWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ActiveMembers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ActiveMembers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ActiveMembers.
   */
  distinct?: Prisma.ActiveMemberScalarFieldEnum | Prisma.ActiveMemberScalarFieldEnum[]
}

/**
 * ActiveMember findFirstOrThrow
 */
export type ActiveMemberFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActiveMember
   */
  select?: Prisma.ActiveMemberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActiveMember
   */
  omit?: Prisma.ActiveMemberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActiveMemberInclude<ExtArgs> | null
  /**
   * Filter, which ActiveMember to fetch.
   */
  where?: Prisma.ActiveMemberWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ActiveMembers to fetch.
   */
  orderBy?: Prisma.ActiveMemberOrderByWithRelationInput | Prisma.ActiveMemberOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ActiveMembers.
   */
  cursor?: Prisma.ActiveMemberWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ActiveMembers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ActiveMembers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ActiveMembers.
   */
  distinct?: Prisma.ActiveMemberScalarFieldEnum | Prisma.ActiveMemberScalarFieldEnum[]
}

/**
 * ActiveMember findMany
 */
export type ActiveMemberFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActiveMember
   */
  select?: Prisma.ActiveMemberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActiveMember
   */
  omit?: Prisma.ActiveMemberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActiveMemberInclude<ExtArgs> | null
  /**
   * Filter, which ActiveMembers to fetch.
   */
  where?: Prisma.ActiveMemberWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ActiveMembers to fetch.
   */
  orderBy?: Prisma.ActiveMemberOrderByWithRelationInput | Prisma.ActiveMemberOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ActiveMembers.
   */
  cursor?: Prisma.ActiveMemberWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ActiveMembers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ActiveMembers.
   */
  skip?: number
  distinct?: Prisma.ActiveMemberScalarFieldEnum | Prisma.ActiveMemberScalarFieldEnum[]
}

/**
 * ActiveMember create
 */
export type ActiveMemberCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActiveMember
   */
  select?: Prisma.ActiveMemberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActiveMember
   */
  omit?: Prisma.ActiveMemberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActiveMemberInclude<ExtArgs> | null
  /**
   * The data needed to create a ActiveMember.
   */
  data: Prisma.XOR<Prisma.ActiveMemberCreateInput, Prisma.ActiveMemberUncheckedCreateInput>
}

/**
 * ActiveMember createMany
 */
export type ActiveMemberCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ActiveMembers.
   */
  data: Prisma.ActiveMemberCreateManyInput | Prisma.ActiveMemberCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ActiveMember createManyAndReturn
 */
export type ActiveMemberCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActiveMember
   */
  select?: Prisma.ActiveMemberSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ActiveMember
   */
  omit?: Prisma.ActiveMemberOmit<ExtArgs> | null
  /**
   * The data used to create many ActiveMembers.
   */
  data: Prisma.ActiveMemberCreateManyInput | Prisma.ActiveMemberCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActiveMemberIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ActiveMember update
 */
export type ActiveMemberUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActiveMember
   */
  select?: Prisma.ActiveMemberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActiveMember
   */
  omit?: Prisma.ActiveMemberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActiveMemberInclude<ExtArgs> | null
  /**
   * The data needed to update a ActiveMember.
   */
  data: Prisma.XOR<Prisma.ActiveMemberUpdateInput, Prisma.ActiveMemberUncheckedUpdateInput>
  /**
   * Choose, which ActiveMember to update.
   */
  where: Prisma.ActiveMemberWhereUniqueInput
}

/**
 * ActiveMember updateMany
 */
export type ActiveMemberUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ActiveMembers.
   */
  data: Prisma.XOR<Prisma.ActiveMemberUpdateManyMutationInput, Prisma.ActiveMemberUncheckedUpdateManyInput>
  /**
   * Filter which ActiveMembers to update
   */
  where?: Prisma.ActiveMemberWhereInput
  /**
   * Limit how many ActiveMembers to update.
   */
  limit?: number
}

/**
 * ActiveMember updateManyAndReturn
 */
export type ActiveMemberUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActiveMember
   */
  select?: Prisma.ActiveMemberSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ActiveMember
   */
  omit?: Prisma.ActiveMemberOmit<ExtArgs> | null
  /**
   * The data used to update ActiveMembers.
   */
  data: Prisma.XOR<Prisma.ActiveMemberUpdateManyMutationInput, Prisma.ActiveMemberUncheckedUpdateManyInput>
  /**
   * Filter which ActiveMembers to update
   */
  where?: Prisma.ActiveMemberWhereInput
  /**
   * Limit how many ActiveMembers to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActiveMemberIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ActiveMember upsert
 */
export type ActiveMemberUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActiveMember
   */
  select?: Prisma.ActiveMemberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActiveMember
   */
  omit?: Prisma.ActiveMemberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActiveMemberInclude<ExtArgs> | null
  /**
   * The filter to search for the ActiveMember to update in case it exists.
   */
  where: Prisma.ActiveMemberWhereUniqueInput
  /**
   * In case the ActiveMember found by the `where` argument doesn't exist, create a new ActiveMember with this data.
   */
  create: Prisma.XOR<Prisma.ActiveMemberCreateInput, Prisma.ActiveMemberUncheckedCreateInput>
  /**
   * In case the ActiveMember was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ActiveMemberUpdateInput, Prisma.ActiveMemberUncheckedUpdateInput>
}

/**
 * ActiveMember delete
 */
export type ActiveMemberDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActiveMember
   */
  select?: Prisma.ActiveMemberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActiveMember
   */
  omit?: Prisma.ActiveMemberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActiveMemberInclude<ExtArgs> | null
  /**
   * Filter which ActiveMember to delete.
   */
  where: Prisma.ActiveMemberWhereUniqueInput
}

/**
 * ActiveMember deleteMany
 */
export type ActiveMemberDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ActiveMembers to delete
   */
  where?: Prisma.ActiveMemberWhereInput
  /**
   * Limit how many ActiveMembers to delete.
   */
  limit?: number
}

/**
 * ActiveMember without action
 */
export type ActiveMemberDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActiveMember
   */
  select?: Prisma.ActiveMemberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActiveMember
   */
  omit?: Prisma.ActiveMemberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActiveMemberInclude<ExtArgs> | null
}
