
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `MemberChannel` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model MemberChannel
 * 
 */
export type MemberChannelModel = runtime.Types.Result.DefaultSelection<Prisma.$MemberChannelPayload>

export type AggregateMemberChannel = {
  _count: MemberChannelCountAggregateOutputType | null
  _min: MemberChannelMinAggregateOutputType | null
  _max: MemberChannelMaxAggregateOutputType | null
}

export type MemberChannelMinAggregateOutputType = {
  id: string | null
  channel_id: string | null
  member_id: string | null
  ban: boolean | null
  unban: Date | null
  add_at: Date | null
}

export type MemberChannelMaxAggregateOutputType = {
  id: string | null
  channel_id: string | null
  member_id: string | null
  ban: boolean | null
  unban: Date | null
  add_at: Date | null
}

export type MemberChannelCountAggregateOutputType = {
  id: number
  channel_id: number
  member_id: number
  ban: number
  unban: number
  add_at: number
  _all: number
}


export type MemberChannelMinAggregateInputType = {
  id?: true
  channel_id?: true
  member_id?: true
  ban?: true
  unban?: true
  add_at?: true
}

export type MemberChannelMaxAggregateInputType = {
  id?: true
  channel_id?: true
  member_id?: true
  ban?: true
  unban?: true
  add_at?: true
}

export type MemberChannelCountAggregateInputType = {
  id?: true
  channel_id?: true
  member_id?: true
  ban?: true
  unban?: true
  add_at?: true
  _all?: true
}

export type MemberChannelAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MemberChannel to aggregate.
   */
  where?: Prisma.MemberChannelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MemberChannels to fetch.
   */
  orderBy?: Prisma.MemberChannelOrderByWithRelationInput | Prisma.MemberChannelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MemberChannelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MemberChannels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MemberChannels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned MemberChannels
  **/
  _count?: true | MemberChannelCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MemberChannelMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MemberChannelMaxAggregateInputType
}

export type GetMemberChannelAggregateType<T extends MemberChannelAggregateArgs> = {
      [P in keyof T & keyof AggregateMemberChannel]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMemberChannel[P]>
    : Prisma.GetScalarType<T[P], AggregateMemberChannel[P]>
}




export type MemberChannelGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MemberChannelWhereInput
  orderBy?: Prisma.MemberChannelOrderByWithAggregationInput | Prisma.MemberChannelOrderByWithAggregationInput[]
  by: Prisma.MemberChannelScalarFieldEnum[] | Prisma.MemberChannelScalarFieldEnum
  having?: Prisma.MemberChannelScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MemberChannelCountAggregateInputType | true
  _min?: MemberChannelMinAggregateInputType
  _max?: MemberChannelMaxAggregateInputType
}

export type MemberChannelGroupByOutputType = {
  id: string
  channel_id: string
  member_id: string
  ban: boolean
  unban: Date | null
  add_at: Date
  _count: MemberChannelCountAggregateOutputType | null
  _min: MemberChannelMinAggregateOutputType | null
  _max: MemberChannelMaxAggregateOutputType | null
}

type GetMemberChannelGroupByPayload<T extends MemberChannelGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MemberChannelGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MemberChannelGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MemberChannelGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MemberChannelGroupByOutputType[P]>
      }
    >
  >



export type MemberChannelWhereInput = {
  AND?: Prisma.MemberChannelWhereInput | Prisma.MemberChannelWhereInput[]
  OR?: Prisma.MemberChannelWhereInput[]
  NOT?: Prisma.MemberChannelWhereInput | Prisma.MemberChannelWhereInput[]
  id?: Prisma.StringFilter<"MemberChannel"> | string
  channel_id?: Prisma.StringFilter<"MemberChannel"> | string
  member_id?: Prisma.StringFilter<"MemberChannel"> | string
  ban?: Prisma.BoolFilter<"MemberChannel"> | boolean
  unban?: Prisma.DateTimeNullableFilter<"MemberChannel"> | Date | string | null
  add_at?: Prisma.DateTimeFilter<"MemberChannel"> | Date | string
  channel?: Prisma.XOR<Prisma.ChannelScalarRelationFilter, Prisma.ChannelWhereInput>
  member?: Prisma.XOR<Prisma.MemberScalarRelationFilter, Prisma.MemberWhereInput>
}

export type MemberChannelOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  channel_id?: Prisma.SortOrder
  member_id?: Prisma.SortOrder
  ban?: Prisma.SortOrder
  unban?: Prisma.SortOrderInput | Prisma.SortOrder
  add_at?: Prisma.SortOrder
  channel?: Prisma.ChannelOrderByWithRelationInput
  member?: Prisma.MemberOrderByWithRelationInput
}

export type MemberChannelWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  channel_id_member_id?: Prisma.MemberChannelChannel_idMember_idCompoundUniqueInput
  AND?: Prisma.MemberChannelWhereInput | Prisma.MemberChannelWhereInput[]
  OR?: Prisma.MemberChannelWhereInput[]
  NOT?: Prisma.MemberChannelWhereInput | Prisma.MemberChannelWhereInput[]
  channel_id?: Prisma.StringFilter<"MemberChannel"> | string
  member_id?: Prisma.StringFilter<"MemberChannel"> | string
  ban?: Prisma.BoolFilter<"MemberChannel"> | boolean
  unban?: Prisma.DateTimeNullableFilter<"MemberChannel"> | Date | string | null
  add_at?: Prisma.DateTimeFilter<"MemberChannel"> | Date | string
  channel?: Prisma.XOR<Prisma.ChannelScalarRelationFilter, Prisma.ChannelWhereInput>
  member?: Prisma.XOR<Prisma.MemberScalarRelationFilter, Prisma.MemberWhereInput>
}, "id" | "channel_id_member_id">

export type MemberChannelOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  channel_id?: Prisma.SortOrder
  member_id?: Prisma.SortOrder
  ban?: Prisma.SortOrder
  unban?: Prisma.SortOrderInput | Prisma.SortOrder
  add_at?: Prisma.SortOrder
  _count?: Prisma.MemberChannelCountOrderByAggregateInput
  _max?: Prisma.MemberChannelMaxOrderByAggregateInput
  _min?: Prisma.MemberChannelMinOrderByAggregateInput
}

export type MemberChannelScalarWhereWithAggregatesInput = {
  AND?: Prisma.MemberChannelScalarWhereWithAggregatesInput | Prisma.MemberChannelScalarWhereWithAggregatesInput[]
  OR?: Prisma.MemberChannelScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MemberChannelScalarWhereWithAggregatesInput | Prisma.MemberChannelScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"MemberChannel"> | string
  channel_id?: Prisma.StringWithAggregatesFilter<"MemberChannel"> | string
  member_id?: Prisma.StringWithAggregatesFilter<"MemberChannel"> | string
  ban?: Prisma.BoolWithAggregatesFilter<"MemberChannel"> | boolean
  unban?: Prisma.DateTimeNullableWithAggregatesFilter<"MemberChannel"> | Date | string | null
  add_at?: Prisma.DateTimeWithAggregatesFilter<"MemberChannel"> | Date | string
}

export type MemberChannelCreateInput = {
  id?: string
  ban?: boolean
  unban?: Date | string | null
  add_at?: Date | string
  channel: Prisma.ChannelCreateNestedOneWithoutMembersInput
  member: Prisma.MemberCreateNestedOneWithoutChannelsInput
}

export type MemberChannelUncheckedCreateInput = {
  id?: string
  channel_id: string
  member_id: string
  ban?: boolean
  unban?: Date | string | null
  add_at?: Date | string
}

export type MemberChannelUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ban?: Prisma.BoolFieldUpdateOperationsInput | boolean
  unban?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  add_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  channel?: Prisma.ChannelUpdateOneRequiredWithoutMembersNestedInput
  member?: Prisma.MemberUpdateOneRequiredWithoutChannelsNestedInput
}

export type MemberChannelUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channel_id?: Prisma.StringFieldUpdateOperationsInput | string
  member_id?: Prisma.StringFieldUpdateOperationsInput | string
  ban?: Prisma.BoolFieldUpdateOperationsInput | boolean
  unban?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  add_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MemberChannelCreateManyInput = {
  id?: string
  channel_id: string
  member_id: string
  ban?: boolean
  unban?: Date | string | null
  add_at?: Date | string
}

export type MemberChannelUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ban?: Prisma.BoolFieldUpdateOperationsInput | boolean
  unban?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  add_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MemberChannelUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channel_id?: Prisma.StringFieldUpdateOperationsInput | string
  member_id?: Prisma.StringFieldUpdateOperationsInput | string
  ban?: Prisma.BoolFieldUpdateOperationsInput | boolean
  unban?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  add_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MemberChannelListRelationFilter = {
  every?: Prisma.MemberChannelWhereInput
  some?: Prisma.MemberChannelWhereInput
  none?: Prisma.MemberChannelWhereInput
}

export type MemberChannelOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type MemberChannelChannel_idMember_idCompoundUniqueInput = {
  channel_id: string
  member_id: string
}

export type MemberChannelCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  channel_id?: Prisma.SortOrder
  member_id?: Prisma.SortOrder
  ban?: Prisma.SortOrder
  unban?: Prisma.SortOrder
  add_at?: Prisma.SortOrder
}

export type MemberChannelMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  channel_id?: Prisma.SortOrder
  member_id?: Prisma.SortOrder
  ban?: Prisma.SortOrder
  unban?: Prisma.SortOrder
  add_at?: Prisma.SortOrder
}

export type MemberChannelMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  channel_id?: Prisma.SortOrder
  member_id?: Prisma.SortOrder
  ban?: Prisma.SortOrder
  unban?: Prisma.SortOrder
  add_at?: Prisma.SortOrder
}

export type MemberChannelCreateNestedManyWithoutChannelInput = {
  create?: Prisma.XOR<Prisma.MemberChannelCreateWithoutChannelInput, Prisma.MemberChannelUncheckedCreateWithoutChannelInput> | Prisma.MemberChannelCreateWithoutChannelInput[] | Prisma.MemberChannelUncheckedCreateWithoutChannelInput[]
  connectOrCreate?: Prisma.MemberChannelCreateOrConnectWithoutChannelInput | Prisma.MemberChannelCreateOrConnectWithoutChannelInput[]
  createMany?: Prisma.MemberChannelCreateManyChannelInputEnvelope
  connect?: Prisma.MemberChannelWhereUniqueInput | Prisma.MemberChannelWhereUniqueInput[]
}

export type MemberChannelUncheckedCreateNestedManyWithoutChannelInput = {
  create?: Prisma.XOR<Prisma.MemberChannelCreateWithoutChannelInput, Prisma.MemberChannelUncheckedCreateWithoutChannelInput> | Prisma.MemberChannelCreateWithoutChannelInput[] | Prisma.MemberChannelUncheckedCreateWithoutChannelInput[]
  connectOrCreate?: Prisma.MemberChannelCreateOrConnectWithoutChannelInput | Prisma.MemberChannelCreateOrConnectWithoutChannelInput[]
  createMany?: Prisma.MemberChannelCreateManyChannelInputEnvelope
  connect?: Prisma.MemberChannelWhereUniqueInput | Prisma.MemberChannelWhereUniqueInput[]
}

export type MemberChannelUpdateManyWithoutChannelNestedInput = {
  create?: Prisma.XOR<Prisma.MemberChannelCreateWithoutChannelInput, Prisma.MemberChannelUncheckedCreateWithoutChannelInput> | Prisma.MemberChannelCreateWithoutChannelInput[] | Prisma.MemberChannelUncheckedCreateWithoutChannelInput[]
  connectOrCreate?: Prisma.MemberChannelCreateOrConnectWithoutChannelInput | Prisma.MemberChannelCreateOrConnectWithoutChannelInput[]
  upsert?: Prisma.MemberChannelUpsertWithWhereUniqueWithoutChannelInput | Prisma.MemberChannelUpsertWithWhereUniqueWithoutChannelInput[]
  createMany?: Prisma.MemberChannelCreateManyChannelInputEnvelope
  set?: Prisma.MemberChannelWhereUniqueInput | Prisma.MemberChannelWhereUniqueInput[]
  disconnect?: Prisma.MemberChannelWhereUniqueInput | Prisma.MemberChannelWhereUniqueInput[]
  delete?: Prisma.MemberChannelWhereUniqueInput | Prisma.MemberChannelWhereUniqueInput[]
  connect?: Prisma.MemberChannelWhereUniqueInput | Prisma.MemberChannelWhereUniqueInput[]
  update?: Prisma.MemberChannelUpdateWithWhereUniqueWithoutChannelInput | Prisma.MemberChannelUpdateWithWhereUniqueWithoutChannelInput[]
  updateMany?: Prisma.MemberChannelUpdateManyWithWhereWithoutChannelInput | Prisma.MemberChannelUpdateManyWithWhereWithoutChannelInput[]
  deleteMany?: Prisma.MemberChannelScalarWhereInput | Prisma.MemberChannelScalarWhereInput[]
}

export type MemberChannelUncheckedUpdateManyWithoutChannelNestedInput = {
  create?: Prisma.XOR<Prisma.MemberChannelCreateWithoutChannelInput, Prisma.MemberChannelUncheckedCreateWithoutChannelInput> | Prisma.MemberChannelCreateWithoutChannelInput[] | Prisma.MemberChannelUncheckedCreateWithoutChannelInput[]
  connectOrCreate?: Prisma.MemberChannelCreateOrConnectWithoutChannelInput | Prisma.MemberChannelCreateOrConnectWithoutChannelInput[]
  upsert?: Prisma.MemberChannelUpsertWithWhereUniqueWithoutChannelInput | Prisma.MemberChannelUpsertWithWhereUniqueWithoutChannelInput[]
  createMany?: Prisma.MemberChannelCreateManyChannelInputEnvelope
  set?: Prisma.MemberChannelWhereUniqueInput | Prisma.MemberChannelWhereUniqueInput[]
  disconnect?: Prisma.MemberChannelWhereUniqueInput | Prisma.MemberChannelWhereUniqueInput[]
  delete?: Prisma.MemberChannelWhereUniqueInput | Prisma.MemberChannelWhereUniqueInput[]
  connect?: Prisma.MemberChannelWhereUniqueInput | Prisma.MemberChannelWhereUniqueInput[]
  update?: Prisma.MemberChannelUpdateWithWhereUniqueWithoutChannelInput | Prisma.MemberChannelUpdateWithWhereUniqueWithoutChannelInput[]
  updateMany?: Prisma.MemberChannelUpdateManyWithWhereWithoutChannelInput | Prisma.MemberChannelUpdateManyWithWhereWithoutChannelInput[]
  deleteMany?: Prisma.MemberChannelScalarWhereInput | Prisma.MemberChannelScalarWhereInput[]
}

export type MemberChannelCreateNestedManyWithoutMemberInput = {
  create?: Prisma.XOR<Prisma.MemberChannelCreateWithoutMemberInput, Prisma.MemberChannelUncheckedCreateWithoutMemberInput> | Prisma.MemberChannelCreateWithoutMemberInput[] | Prisma.MemberChannelUncheckedCreateWithoutMemberInput[]
  connectOrCreate?: Prisma.MemberChannelCreateOrConnectWithoutMemberInput | Prisma.MemberChannelCreateOrConnectWithoutMemberInput[]
  createMany?: Prisma.MemberChannelCreateManyMemberInputEnvelope
  connect?: Prisma.MemberChannelWhereUniqueInput | Prisma.MemberChannelWhereUniqueInput[]
}

export type MemberChannelUncheckedCreateNestedManyWithoutMemberInput = {
  create?: Prisma.XOR<Prisma.MemberChannelCreateWithoutMemberInput, Prisma.MemberChannelUncheckedCreateWithoutMemberInput> | Prisma.MemberChannelCreateWithoutMemberInput[] | Prisma.MemberChannelUncheckedCreateWithoutMemberInput[]
  connectOrCreate?: Prisma.MemberChannelCreateOrConnectWithoutMemberInput | Prisma.MemberChannelCreateOrConnectWithoutMemberInput[]
  createMany?: Prisma.MemberChannelCreateManyMemberInputEnvelope
  connect?: Prisma.MemberChannelWhereUniqueInput | Prisma.MemberChannelWhereUniqueInput[]
}

export type MemberChannelUpdateManyWithoutMemberNestedInput = {
  create?: Prisma.XOR<Prisma.MemberChannelCreateWithoutMemberInput, Prisma.MemberChannelUncheckedCreateWithoutMemberInput> | Prisma.MemberChannelCreateWithoutMemberInput[] | Prisma.MemberChannelUncheckedCreateWithoutMemberInput[]
  connectOrCreate?: Prisma.MemberChannelCreateOrConnectWithoutMemberInput | Prisma.MemberChannelCreateOrConnectWithoutMemberInput[]
  upsert?: Prisma.MemberChannelUpsertWithWhereUniqueWithoutMemberInput | Prisma.MemberChannelUpsertWithWhereUniqueWithoutMemberInput[]
  createMany?: Prisma.MemberChannelCreateManyMemberInputEnvelope
  set?: Prisma.MemberChannelWhereUniqueInput | Prisma.MemberChannelWhereUniqueInput[]
  disconnect?: Prisma.MemberChannelWhereUniqueInput | Prisma.MemberChannelWhereUniqueInput[]
  delete?: Prisma.MemberChannelWhereUniqueInput | Prisma.MemberChannelWhereUniqueInput[]
  connect?: Prisma.MemberChannelWhereUniqueInput | Prisma.MemberChannelWhereUniqueInput[]
  update?: Prisma.MemberChannelUpdateWithWhereUniqueWithoutMemberInput | Prisma.MemberChannelUpdateWithWhereUniqueWithoutMemberInput[]
  updateMany?: Prisma.MemberChannelUpdateManyWithWhereWithoutMemberInput | Prisma.MemberChannelUpdateManyWithWhereWithoutMemberInput[]
  deleteMany?: Prisma.MemberChannelScalarWhereInput | Prisma.MemberChannelScalarWhereInput[]
}

export type MemberChannelUncheckedUpdateManyWithoutMemberNestedInput = {
  create?: Prisma.XOR<Prisma.MemberChannelCreateWithoutMemberInput, Prisma.MemberChannelUncheckedCreateWithoutMemberInput> | Prisma.MemberChannelCreateWithoutMemberInput[] | Prisma.MemberChannelUncheckedCreateWithoutMemberInput[]
  connectOrCreate?: Prisma.MemberChannelCreateOrConnectWithoutMemberInput | Prisma.MemberChannelCreateOrConnectWithoutMemberInput[]
  upsert?: Prisma.MemberChannelUpsertWithWhereUniqueWithoutMemberInput | Prisma.MemberChannelUpsertWithWhereUniqueWithoutMemberInput[]
  createMany?: Prisma.MemberChannelCreateManyMemberInputEnvelope
  set?: Prisma.MemberChannelWhereUniqueInput | Prisma.MemberChannelWhereUniqueInput[]
  disconnect?: Prisma.MemberChannelWhereUniqueInput | Prisma.MemberChannelWhereUniqueInput[]
  delete?: Prisma.MemberChannelWhereUniqueInput | Prisma.MemberChannelWhereUniqueInput[]
  connect?: Prisma.MemberChannelWhereUniqueInput | Prisma.MemberChannelWhereUniqueInput[]
  update?: Prisma.MemberChannelUpdateWithWhereUniqueWithoutMemberInput | Prisma.MemberChannelUpdateWithWhereUniqueWithoutMemberInput[]
  updateMany?: Prisma.MemberChannelUpdateManyWithWhereWithoutMemberInput | Prisma.MemberChannelUpdateManyWithWhereWithoutMemberInput[]
  deleteMany?: Prisma.MemberChannelScalarWhereInput | Prisma.MemberChannelScalarWhereInput[]
}

export type MemberChannelCreateWithoutChannelInput = {
  id?: string
  ban?: boolean
  unban?: Date | string | null
  add_at?: Date | string
  member: Prisma.MemberCreateNestedOneWithoutChannelsInput
}

export type MemberChannelUncheckedCreateWithoutChannelInput = {
  id?: string
  member_id: string
  ban?: boolean
  unban?: Date | string | null
  add_at?: Date | string
}

export type MemberChannelCreateOrConnectWithoutChannelInput = {
  where: Prisma.MemberChannelWhereUniqueInput
  create: Prisma.XOR<Prisma.MemberChannelCreateWithoutChannelInput, Prisma.MemberChannelUncheckedCreateWithoutChannelInput>
}

export type MemberChannelCreateManyChannelInputEnvelope = {
  data: Prisma.MemberChannelCreateManyChannelInput | Prisma.MemberChannelCreateManyChannelInput[]
  skipDuplicates?: boolean
}

export type MemberChannelUpsertWithWhereUniqueWithoutChannelInput = {
  where: Prisma.MemberChannelWhereUniqueInput
  update: Prisma.XOR<Prisma.MemberChannelUpdateWithoutChannelInput, Prisma.MemberChannelUncheckedUpdateWithoutChannelInput>
  create: Prisma.XOR<Prisma.MemberChannelCreateWithoutChannelInput, Prisma.MemberChannelUncheckedCreateWithoutChannelInput>
}

export type MemberChannelUpdateWithWhereUniqueWithoutChannelInput = {
  where: Prisma.MemberChannelWhereUniqueInput
  data: Prisma.XOR<Prisma.MemberChannelUpdateWithoutChannelInput, Prisma.MemberChannelUncheckedUpdateWithoutChannelInput>
}

export type MemberChannelUpdateManyWithWhereWithoutChannelInput = {
  where: Prisma.MemberChannelScalarWhereInput
  data: Prisma.XOR<Prisma.MemberChannelUpdateManyMutationInput, Prisma.MemberChannelUncheckedUpdateManyWithoutChannelInput>
}

export type MemberChannelScalarWhereInput = {
  AND?: Prisma.MemberChannelScalarWhereInput | Prisma.MemberChannelScalarWhereInput[]
  OR?: Prisma.MemberChannelScalarWhereInput[]
  NOT?: Prisma.MemberChannelScalarWhereInput | Prisma.MemberChannelScalarWhereInput[]
  id?: Prisma.StringFilter<"MemberChannel"> | string
  channel_id?: Prisma.StringFilter<"MemberChannel"> | string
  member_id?: Prisma.StringFilter<"MemberChannel"> | string
  ban?: Prisma.BoolFilter<"MemberChannel"> | boolean
  unban?: Prisma.DateTimeNullableFilter<"MemberChannel"> | Date | string | null
  add_at?: Prisma.DateTimeFilter<"MemberChannel"> | Date | string
}

export type MemberChannelCreateWithoutMemberInput = {
  id?: string
  ban?: boolean
  unban?: Date | string | null
  add_at?: Date | string
  channel: Prisma.ChannelCreateNestedOneWithoutMembersInput
}

export type MemberChannelUncheckedCreateWithoutMemberInput = {
  id?: string
  channel_id: string
  ban?: boolean
  unban?: Date | string | null
  add_at?: Date | string
}

export type MemberChannelCreateOrConnectWithoutMemberInput = {
  where: Prisma.MemberChannelWhereUniqueInput
  create: Prisma.XOR<Prisma.MemberChannelCreateWithoutMemberInput, Prisma.MemberChannelUncheckedCreateWithoutMemberInput>
}

export type MemberChannelCreateManyMemberInputEnvelope = {
  data: Prisma.MemberChannelCreateManyMemberInput | Prisma.MemberChannelCreateManyMemberInput[]
  skipDuplicates?: boolean
}

export type MemberChannelUpsertWithWhereUniqueWithoutMemberInput = {
  where: Prisma.MemberChannelWhereUniqueInput
  update: Prisma.XOR<Prisma.MemberChannelUpdateWithoutMemberInput, Prisma.MemberChannelUncheckedUpdateWithoutMemberInput>
  create: Prisma.XOR<Prisma.MemberChannelCreateWithoutMemberInput, Prisma.MemberChannelUncheckedCreateWithoutMemberInput>
}

export type MemberChannelUpdateWithWhereUniqueWithoutMemberInput = {
  where: Prisma.MemberChannelWhereUniqueInput
  data: Prisma.XOR<Prisma.MemberChannelUpdateWithoutMemberInput, Prisma.MemberChannelUncheckedUpdateWithoutMemberInput>
}

export type MemberChannelUpdateManyWithWhereWithoutMemberInput = {
  where: Prisma.MemberChannelScalarWhereInput
  data: Prisma.XOR<Prisma.MemberChannelUpdateManyMutationInput, Prisma.MemberChannelUncheckedUpdateManyWithoutMemberInput>
}

export type MemberChannelCreateManyChannelInput = {
  id?: string
  member_id: string
  ban?: boolean
  unban?: Date | string | null
  add_at?: Date | string
}

export type MemberChannelUpdateWithoutChannelInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ban?: Prisma.BoolFieldUpdateOperationsInput | boolean
  unban?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  add_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  member?: Prisma.MemberUpdateOneRequiredWithoutChannelsNestedInput
}

export type MemberChannelUncheckedUpdateWithoutChannelInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  member_id?: Prisma.StringFieldUpdateOperationsInput | string
  ban?: Prisma.BoolFieldUpdateOperationsInput | boolean
  unban?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  add_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MemberChannelUncheckedUpdateManyWithoutChannelInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  member_id?: Prisma.StringFieldUpdateOperationsInput | string
  ban?: Prisma.BoolFieldUpdateOperationsInput | boolean
  unban?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  add_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MemberChannelCreateManyMemberInput = {
  id?: string
  channel_id: string
  ban?: boolean
  unban?: Date | string | null
  add_at?: Date | string
}

export type MemberChannelUpdateWithoutMemberInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ban?: Prisma.BoolFieldUpdateOperationsInput | boolean
  unban?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  add_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  channel?: Prisma.ChannelUpdateOneRequiredWithoutMembersNestedInput
}

export type MemberChannelUncheckedUpdateWithoutMemberInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channel_id?: Prisma.StringFieldUpdateOperationsInput | string
  ban?: Prisma.BoolFieldUpdateOperationsInput | boolean
  unban?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  add_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MemberChannelUncheckedUpdateManyWithoutMemberInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channel_id?: Prisma.StringFieldUpdateOperationsInput | string
  ban?: Prisma.BoolFieldUpdateOperationsInput | boolean
  unban?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  add_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type MemberChannelSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  channel_id?: boolean
  member_id?: boolean
  ban?: boolean
  unban?: boolean
  add_at?: boolean
  channel?: boolean | Prisma.ChannelDefaultArgs<ExtArgs>
  member?: boolean | Prisma.MemberDefaultArgs<ExtArgs>
}, ExtArgs["result"]["memberChannel"]>

export type MemberChannelSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  channel_id?: boolean
  member_id?: boolean
  ban?: boolean
  unban?: boolean
  add_at?: boolean
  channel?: boolean | Prisma.ChannelDefaultArgs<ExtArgs>
  member?: boolean | Prisma.MemberDefaultArgs<ExtArgs>
}, ExtArgs["result"]["memberChannel"]>

export type MemberChannelSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  channel_id?: boolean
  member_id?: boolean
  ban?: boolean
  unban?: boolean
  add_at?: boolean
  channel?: boolean | Prisma.ChannelDefaultArgs<ExtArgs>
  member?: boolean | Prisma.MemberDefaultArgs<ExtArgs>
}, ExtArgs["result"]["memberChannel"]>

export type MemberChannelSelectScalar = {
  id?: boolean
  channel_id?: boolean
  member_id?: boolean
  ban?: boolean
  unban?: boolean
  add_at?: boolean
}

export type MemberChannelOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "channel_id" | "member_id" | "ban" | "unban" | "add_at", ExtArgs["result"]["memberChannel"]>
export type MemberChannelInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  channel?: boolean | Prisma.ChannelDefaultArgs<ExtArgs>
  member?: boolean | Prisma.MemberDefaultArgs<ExtArgs>
}
export type MemberChannelIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  channel?: boolean | Prisma.ChannelDefaultArgs<ExtArgs>
  member?: boolean | Prisma.MemberDefaultArgs<ExtArgs>
}
export type MemberChannelIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  channel?: boolean | Prisma.ChannelDefaultArgs<ExtArgs>
  member?: boolean | Prisma.MemberDefaultArgs<ExtArgs>
}

export type $MemberChannelPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "MemberChannel"
  objects: {
    channel: Prisma.$ChannelPayload<ExtArgs>
    member: Prisma.$MemberPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    channel_id: string
    member_id: string
    ban: boolean
    unban: Date | null
    add_at: Date
  }, ExtArgs["result"]["memberChannel"]>
  composites: {}
}

export type MemberChannelGetPayload<S extends boolean | null | undefined | MemberChannelDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MemberChannelPayload, S>

export type MemberChannelCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MemberChannelFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MemberChannelCountAggregateInputType | true
  }

export interface MemberChannelDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['MemberChannel'], meta: { name: 'MemberChannel' } }
  /**
   * Find zero or one MemberChannel that matches the filter.
   * @param {MemberChannelFindUniqueArgs} args - Arguments to find a MemberChannel
   * @example
   * // Get one MemberChannel
   * const memberChannel = await prisma.memberChannel.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MemberChannelFindUniqueArgs>(args: Prisma.SelectSubset<T, MemberChannelFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MemberChannelClient<runtime.Types.Result.GetResult<Prisma.$MemberChannelPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one MemberChannel that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MemberChannelFindUniqueOrThrowArgs} args - Arguments to find a MemberChannel
   * @example
   * // Get one MemberChannel
   * const memberChannel = await prisma.memberChannel.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MemberChannelFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MemberChannelFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MemberChannelClient<runtime.Types.Result.GetResult<Prisma.$MemberChannelPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MemberChannel that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MemberChannelFindFirstArgs} args - Arguments to find a MemberChannel
   * @example
   * // Get one MemberChannel
   * const memberChannel = await prisma.memberChannel.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MemberChannelFindFirstArgs>(args?: Prisma.SelectSubset<T, MemberChannelFindFirstArgs<ExtArgs>>): Prisma.Prisma__MemberChannelClient<runtime.Types.Result.GetResult<Prisma.$MemberChannelPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MemberChannel that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MemberChannelFindFirstOrThrowArgs} args - Arguments to find a MemberChannel
   * @example
   * // Get one MemberChannel
   * const memberChannel = await prisma.memberChannel.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MemberChannelFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MemberChannelFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MemberChannelClient<runtime.Types.Result.GetResult<Prisma.$MemberChannelPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more MemberChannels that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MemberChannelFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all MemberChannels
   * const memberChannels = await prisma.memberChannel.findMany()
   * 
   * // Get first 10 MemberChannels
   * const memberChannels = await prisma.memberChannel.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const memberChannelWithIdOnly = await prisma.memberChannel.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MemberChannelFindManyArgs>(args?: Prisma.SelectSubset<T, MemberChannelFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MemberChannelPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a MemberChannel.
   * @param {MemberChannelCreateArgs} args - Arguments to create a MemberChannel.
   * @example
   * // Create one MemberChannel
   * const MemberChannel = await prisma.memberChannel.create({
   *   data: {
   *     // ... data to create a MemberChannel
   *   }
   * })
   * 
   */
  create<T extends MemberChannelCreateArgs>(args: Prisma.SelectSubset<T, MemberChannelCreateArgs<ExtArgs>>): Prisma.Prisma__MemberChannelClient<runtime.Types.Result.GetResult<Prisma.$MemberChannelPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many MemberChannels.
   * @param {MemberChannelCreateManyArgs} args - Arguments to create many MemberChannels.
   * @example
   * // Create many MemberChannels
   * const memberChannel = await prisma.memberChannel.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MemberChannelCreateManyArgs>(args?: Prisma.SelectSubset<T, MemberChannelCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many MemberChannels and returns the data saved in the database.
   * @param {MemberChannelCreateManyAndReturnArgs} args - Arguments to create many MemberChannels.
   * @example
   * // Create many MemberChannels
   * const memberChannel = await prisma.memberChannel.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many MemberChannels and only return the `id`
   * const memberChannelWithIdOnly = await prisma.memberChannel.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MemberChannelCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MemberChannelCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MemberChannelPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a MemberChannel.
   * @param {MemberChannelDeleteArgs} args - Arguments to delete one MemberChannel.
   * @example
   * // Delete one MemberChannel
   * const MemberChannel = await prisma.memberChannel.delete({
   *   where: {
   *     // ... filter to delete one MemberChannel
   *   }
   * })
   * 
   */
  delete<T extends MemberChannelDeleteArgs>(args: Prisma.SelectSubset<T, MemberChannelDeleteArgs<ExtArgs>>): Prisma.Prisma__MemberChannelClient<runtime.Types.Result.GetResult<Prisma.$MemberChannelPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one MemberChannel.
   * @param {MemberChannelUpdateArgs} args - Arguments to update one MemberChannel.
   * @example
   * // Update one MemberChannel
   * const memberChannel = await prisma.memberChannel.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MemberChannelUpdateArgs>(args: Prisma.SelectSubset<T, MemberChannelUpdateArgs<ExtArgs>>): Prisma.Prisma__MemberChannelClient<runtime.Types.Result.GetResult<Prisma.$MemberChannelPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more MemberChannels.
   * @param {MemberChannelDeleteManyArgs} args - Arguments to filter MemberChannels to delete.
   * @example
   * // Delete a few MemberChannels
   * const { count } = await prisma.memberChannel.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MemberChannelDeleteManyArgs>(args?: Prisma.SelectSubset<T, MemberChannelDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MemberChannels.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MemberChannelUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many MemberChannels
   * const memberChannel = await prisma.memberChannel.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MemberChannelUpdateManyArgs>(args: Prisma.SelectSubset<T, MemberChannelUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MemberChannels and returns the data updated in the database.
   * @param {MemberChannelUpdateManyAndReturnArgs} args - Arguments to update many MemberChannels.
   * @example
   * // Update many MemberChannels
   * const memberChannel = await prisma.memberChannel.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more MemberChannels and only return the `id`
   * const memberChannelWithIdOnly = await prisma.memberChannel.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MemberChannelUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MemberChannelUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MemberChannelPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one MemberChannel.
   * @param {MemberChannelUpsertArgs} args - Arguments to update or create a MemberChannel.
   * @example
   * // Update or create a MemberChannel
   * const memberChannel = await prisma.memberChannel.upsert({
   *   create: {
   *     // ... data to create a MemberChannel
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the MemberChannel we want to update
   *   }
   * })
   */
  upsert<T extends MemberChannelUpsertArgs>(args: Prisma.SelectSubset<T, MemberChannelUpsertArgs<ExtArgs>>): Prisma.Prisma__MemberChannelClient<runtime.Types.Result.GetResult<Prisma.$MemberChannelPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of MemberChannels.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MemberChannelCountArgs} args - Arguments to filter MemberChannels to count.
   * @example
   * // Count the number of MemberChannels
   * const count = await prisma.memberChannel.count({
   *   where: {
   *     // ... the filter for the MemberChannels we want to count
   *   }
   * })
  **/
  count<T extends MemberChannelCountArgs>(
    args?: Prisma.Subset<T, MemberChannelCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MemberChannelCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a MemberChannel.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MemberChannelAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MemberChannelAggregateArgs>(args: Prisma.Subset<T, MemberChannelAggregateArgs>): Prisma.PrismaPromise<GetMemberChannelAggregateType<T>>

  /**
   * Group by MemberChannel.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MemberChannelGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MemberChannelGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MemberChannelGroupByArgs['orderBy'] }
      : { orderBy?: MemberChannelGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MemberChannelGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMemberChannelGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the MemberChannel model
 */
readonly fields: MemberChannelFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for MemberChannel.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MemberChannelClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  channel<T extends Prisma.ChannelDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ChannelDefaultArgs<ExtArgs>>): Prisma.Prisma__ChannelClient<runtime.Types.Result.GetResult<Prisma.$ChannelPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  member<T extends Prisma.MemberDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MemberDefaultArgs<ExtArgs>>): Prisma.Prisma__MemberClient<runtime.Types.Result.GetResult<Prisma.$MemberPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the MemberChannel model
 */
export interface MemberChannelFieldRefs {
  readonly id: Prisma.FieldRef<"MemberChannel", 'String'>
  readonly channel_id: Prisma.FieldRef<"MemberChannel", 'String'>
  readonly member_id: Prisma.FieldRef<"MemberChannel", 'String'>
  readonly ban: Prisma.FieldRef<"MemberChannel", 'Boolean'>
  readonly unban: Prisma.FieldRef<"MemberChannel", 'DateTime'>
  readonly add_at: Prisma.FieldRef<"MemberChannel", 'DateTime'>
}
    

// Custom InputTypes
/**
 * MemberChannel findUnique
 */
export type MemberChannelFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MemberChannel
   */
  select?: Prisma.MemberChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MemberChannel
   */
  omit?: Prisma.MemberChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MemberChannelInclude<ExtArgs> | null
  /**
   * Filter, which MemberChannel to fetch.
   */
  where: Prisma.MemberChannelWhereUniqueInput
}

/**
 * MemberChannel findUniqueOrThrow
 */
export type MemberChannelFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MemberChannel
   */
  select?: Prisma.MemberChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MemberChannel
   */
  omit?: Prisma.MemberChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MemberChannelInclude<ExtArgs> | null
  /**
   * Filter, which MemberChannel to fetch.
   */
  where: Prisma.MemberChannelWhereUniqueInput
}

/**
 * MemberChannel findFirst
 */
export type MemberChannelFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MemberChannel
   */
  select?: Prisma.MemberChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MemberChannel
   */
  omit?: Prisma.MemberChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MemberChannelInclude<ExtArgs> | null
  /**
   * Filter, which MemberChannel to fetch.
   */
  where?: Prisma.MemberChannelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MemberChannels to fetch.
   */
  orderBy?: Prisma.MemberChannelOrderByWithRelationInput | Prisma.MemberChannelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MemberChannels.
   */
  cursor?: Prisma.MemberChannelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MemberChannels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MemberChannels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MemberChannels.
   */
  distinct?: Prisma.MemberChannelScalarFieldEnum | Prisma.MemberChannelScalarFieldEnum[]
}

/**
 * MemberChannel findFirstOrThrow
 */
export type MemberChannelFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MemberChannel
   */
  select?: Prisma.MemberChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MemberChannel
   */
  omit?: Prisma.MemberChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MemberChannelInclude<ExtArgs> | null
  /**
   * Filter, which MemberChannel to fetch.
   */
  where?: Prisma.MemberChannelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MemberChannels to fetch.
   */
  orderBy?: Prisma.MemberChannelOrderByWithRelationInput | Prisma.MemberChannelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MemberChannels.
   */
  cursor?: Prisma.MemberChannelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MemberChannels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MemberChannels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MemberChannels.
   */
  distinct?: Prisma.MemberChannelScalarFieldEnum | Prisma.MemberChannelScalarFieldEnum[]
}

/**
 * MemberChannel findMany
 */
export type MemberChannelFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MemberChannel
   */
  select?: Prisma.MemberChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MemberChannel
   */
  omit?: Prisma.MemberChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MemberChannelInclude<ExtArgs> | null
  /**
   * Filter, which MemberChannels to fetch.
   */
  where?: Prisma.MemberChannelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MemberChannels to fetch.
   */
  orderBy?: Prisma.MemberChannelOrderByWithRelationInput | Prisma.MemberChannelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing MemberChannels.
   */
  cursor?: Prisma.MemberChannelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MemberChannels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MemberChannels.
   */
  skip?: number
  distinct?: Prisma.MemberChannelScalarFieldEnum | Prisma.MemberChannelScalarFieldEnum[]
}

/**
 * MemberChannel create
 */
export type MemberChannelCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MemberChannel
   */
  select?: Prisma.MemberChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MemberChannel
   */
  omit?: Prisma.MemberChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MemberChannelInclude<ExtArgs> | null
  /**
   * The data needed to create a MemberChannel.
   */
  data: Prisma.XOR<Prisma.MemberChannelCreateInput, Prisma.MemberChannelUncheckedCreateInput>
}

/**
 * MemberChannel createMany
 */
export type MemberChannelCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many MemberChannels.
   */
  data: Prisma.MemberChannelCreateManyInput | Prisma.MemberChannelCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MemberChannel createManyAndReturn
 */
export type MemberChannelCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MemberChannel
   */
  select?: Prisma.MemberChannelSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MemberChannel
   */
  omit?: Prisma.MemberChannelOmit<ExtArgs> | null
  /**
   * The data used to create many MemberChannels.
   */
  data: Prisma.MemberChannelCreateManyInput | Prisma.MemberChannelCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MemberChannelIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * MemberChannel update
 */
export type MemberChannelUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MemberChannel
   */
  select?: Prisma.MemberChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MemberChannel
   */
  omit?: Prisma.MemberChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MemberChannelInclude<ExtArgs> | null
  /**
   * The data needed to update a MemberChannel.
   */
  data: Prisma.XOR<Prisma.MemberChannelUpdateInput, Prisma.MemberChannelUncheckedUpdateInput>
  /**
   * Choose, which MemberChannel to update.
   */
  where: Prisma.MemberChannelWhereUniqueInput
}

/**
 * MemberChannel updateMany
 */
export type MemberChannelUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update MemberChannels.
   */
  data: Prisma.XOR<Prisma.MemberChannelUpdateManyMutationInput, Prisma.MemberChannelUncheckedUpdateManyInput>
  /**
   * Filter which MemberChannels to update
   */
  where?: Prisma.MemberChannelWhereInput
  /**
   * Limit how many MemberChannels to update.
   */
  limit?: number
}

/**
 * MemberChannel updateManyAndReturn
 */
export type MemberChannelUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MemberChannel
   */
  select?: Prisma.MemberChannelSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MemberChannel
   */
  omit?: Prisma.MemberChannelOmit<ExtArgs> | null
  /**
   * The data used to update MemberChannels.
   */
  data: Prisma.XOR<Prisma.MemberChannelUpdateManyMutationInput, Prisma.MemberChannelUncheckedUpdateManyInput>
  /**
   * Filter which MemberChannels to update
   */
  where?: Prisma.MemberChannelWhereInput
  /**
   * Limit how many MemberChannels to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MemberChannelIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * MemberChannel upsert
 */
export type MemberChannelUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MemberChannel
   */
  select?: Prisma.MemberChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MemberChannel
   */
  omit?: Prisma.MemberChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MemberChannelInclude<ExtArgs> | null
  /**
   * The filter to search for the MemberChannel to update in case it exists.
   */
  where: Prisma.MemberChannelWhereUniqueInput
  /**
   * In case the MemberChannel found by the `where` argument doesn't exist, create a new MemberChannel with this data.
   */
  create: Prisma.XOR<Prisma.MemberChannelCreateInput, Prisma.MemberChannelUncheckedCreateInput>
  /**
   * In case the MemberChannel was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MemberChannelUpdateInput, Prisma.MemberChannelUncheckedUpdateInput>
}

/**
 * MemberChannel delete
 */
export type MemberChannelDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MemberChannel
   */
  select?: Prisma.MemberChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MemberChannel
   */
  omit?: Prisma.MemberChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MemberChannelInclude<ExtArgs> | null
  /**
   * Filter which MemberChannel to delete.
   */
  where: Prisma.MemberChannelWhereUniqueInput
}

/**
 * MemberChannel deleteMany
 */
export type MemberChannelDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MemberChannels to delete
   */
  where?: Prisma.MemberChannelWhereInput
  /**
   * Limit how many MemberChannels to delete.
   */
  limit?: number
}

/**
 * MemberChannel without action
 */
export type MemberChannelDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MemberChannel
   */
  select?: Prisma.MemberChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MemberChannel
   */
  omit?: Prisma.MemberChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MemberChannelInclude<ExtArgs> | null
}
